version: "3.4"
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
#passing enironmental variables to the container
    environment:
      - TZ=Canada/Mountain

# this is the custom build app which contains our automation test scripts
  e2e:
    image: e2e-test
    container_name: rozetka_wdio_project
    build: . # it takes the path of the dockerfile and builds it
    depends_on:
      - selenoid
    links:
      - selenoid
    networks:
      - selenoid
    volumes:
      - "./allure-results:/usr/lib/rozetka_wdio_project/allure-results" # volume mapping the allure results
      - "./logs:/usr/lib/rozetka_wdio_project/logs"

networks:
  selenoid:
    name: selenoid